### ISSUE TITLE
Error in replicate tutorial

### ISSUE THREAD

**Issue by Haz1y** [jianhuupenn/TESLA#13]
Hi [Author's Name],

I hope this message finds you well. I've been trying to replicate the results you've achieved in your project, particularly regarding the neatness of the boundaries you've plotted. However, I seem to be encountering some difficulties in reproducing them accurately.
<img width="857" alt="image" src="https://github.com/jianhuupenn/TESLA/assets/50012377/2c0d69e5-0b65-4438-8027-7e9ebc53d84e">
<img width="1032" alt="image" src="https://github.com/jianhuupenn/TESLA/assets/50012377/bc2e9db9-daa3-4ca0-97e5-a994e0d784e8">
Regardless of adjustments made to either the apertureSize or L2gradient parameters, the observed outcomes remain consistent. Could this discrepancy potentially be attributed to variations in OpenCV versions？

**Comment by jianhuupenn** [comment]
Thanks for your interest in TESLA!
The contour in the tutorial was detected using:
```
cnt=tesla.cv2_detect_contour(img, apertureSize=5,L2gradient = True)
```
The image you show, which also looks good to me,  seems generated from the scan_contour() function.
The slight difference in the boundary region will not affect the results much.Feel free to proceed with your current contour
