### ISSUE TITLE
[TESLA] Transfer core/edge to original visium spot

### ISSUE THREAD

**Issue by jpark27** [jianhuupenn/TESLA#15]
Dear @jianhuupenn,

Hello, again! Sorry for bugging you again.
With previous support, I manage to sucessfully run all steps with toy and in-house data :-)

At last, I have been wanting to transfer super-resolution tumour core/edge information to original spots. 

![image](https://github.com/jianhuupenn/TESLA/assets/59645310/136fe697-3d03-4255-8f98-1c9cc428e07c)
![image](https://github.com/jianhuupenn/TESLA/assets/59645310/611f5add-eab6-4e3d-91c3-c895a46e653b)

Although I recognise you commented on this issue (https://github.com/jianhuupenn/TESLA/issues/7) before, but would you mind give practically how one would do such 'transfer'? 

I am asking you this as initially I thought I would use pixel 'x_y' in between 'adata (visium)' and 'enhanced_exp_adata' but seemingly there's no points are having exactly same x, y values at the end.
`adata.obs['x_y']=adata.obs['x4'].astype(str)+str('_')+adata.obs['x5'].astype(str)
enhanced_exp_adata.obs['x_y']=enhanced_exp_adata.obs['x'].astype(str)+str('_')+enhanced_exp_adata.obs['y'].astype(str)`

Any tips would be really appreciated!

best wishes,
J

**Comment by jianhuupenn** [comment]
Here is the pseudo code:
```
ret=[]
for each spot:
    get its x and y coordinates
    identify=annotated image [x, y], this identify can be tumor core, edge, or neither
    ret.append(identify)

return ret
```

**Comment by fcgportal** [comment]
> Here is the pseudo code:
> 
> ```
> ret=[]
> for each spot:
>     get its x and y coordinates
>     identify=annotated image [x, y], this identify can be tumor core, edge, or neither
>     ret.append(identify)
> 
> return ret
> ```

Would you please give an example how to use this pseudo code? Many thanks!
